name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    outputs:
      tag_name: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install project dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build macOS executable
        run: pkg package.json

      - name: Get the version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Rename the package
        run: mv release/inkdrop-visualizer-macos release/inkdrop

      - name: Archive the macOS executable
        run: tar -czvf release/inkdrop-brew-${{ steps.get_version.outputs.VERSION }}.tar.gz -C release inkdrop
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: inkdrop-${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload macOS archive to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/inkdrop-brew-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: inkdrop-brew-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip

  update-homebrew:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Homebrew tap
        uses: actions/checkout@v2
        with:
          repository: inkdrop-org/homebrew-inkdrop-visualizer
          token: ${{ secrets.HOMEBREW_REPO_TOKEN }}

      - name: Download the macOS package
        run: |
          wget "https://github.com/inkdrop-org/terraform-visualizer-cli/releases/download/${{ needs.release.outputs.tag_name }}/inkdrop-brew-${{ needs.release.outputs.tag_name }}.tar.gz" -O /tmp/inkdrop-brew-${{ needs.release.outputs.tag_name }}.tar.gz

      - name: Compute SHA256
        id: sha256
        run: echo "::set-output name=sha::$(sha256sum /tmp/inkdrop-brew-${{ needs.release.outputs.tag_name }}.tar.gz | awk '{print $1}')"

      - name: Update formula
        run: |
          FORMULA_PATH="${{ github.workspace }}/Formula/inkdrop-visualizer.rb"
          PACKAGE_URL="https://github.com/inkdrop-org/terraform-visualizer-cli/releases/download/${{ needs.release.outputs.tag_name }}/inkdrop-brew-${{ needs.release.outputs.tag_name }}.tar.gz"
          SHA256="${{ steps.sha256.outputs.sha }}"
          VERSION="${{ needs.release.outputs.tag_name }}"
          STRIPPED_VERSION="${VERSION#v}"
          sed -i "s|^  url .*|  url \"$PACKAGE_URL\"|" $FORMULA_PATH
          sed -i "s|^  sha256 .*|  sha256 \"$SHA256\"|" $FORMULA_PATH
          sed -i "s|^  version .*|  version \"$STRIPPED_VERSION\"|" $FORMULA_PATH

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/inkdrop-visualizer.rb
          git commit -m "Update inkdrop-visualizer to ${{ needs.release.outputs.tag_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_REPO_TOKEN }}