export const demoShapes = [
    {
        "x": 3036.222462640292,
        "y": -509.173528430375,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:AKWTaSiXQ7JMxwCM9HMFn",
        "type": "geo",
        "props": {
            "w": 679.6247878980514,
            "h": 457.9160727132356,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "semi",
            "dash": "solid",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "middle",
            "verticalAlign": "middle",
            "growY": 0,
            "url": ""
        },
        "parentId": "page:page",
        "index": "a9",
        "typeName": "shape"
    },
    {
        "x": 3104.6306887106657,
        "y": -441.5207362994162,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:4R6-1gO1Ni6WkixndPfTf",
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 331.9085885485479,
            "text": "Quick links:",
            "font": "mono",
            "align": "middle",
            "autoSize": true,
            "scale": 3.018267728182068
        },
        "parentId": "page:page",
        "index": "aA",
        "typeName": "shape"
    },
    {
        "x": 3105.8052081587985,
        "y": -343.73357794964204,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:0F6HGfXrn4YG9yP3hdvMT",
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 196.30453466358782,
            "text": "GitHub repo\nBook a call\nWebsite",
            "font": "sans",
            "align": "start",
            "autoSize": true,
            "scale": 2.3131087736514435
        },
        "parentId": "page:page",
        "index": "aB",
        "typeName": "shape"
    },
    {
        "x": 3445.1029583728982,
        "y": -321.085354627804,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:SM-b8UyFD3ZUqbJwYnYJi",
        "type": "geo",
        "props": {
            "w": 44.58805662389258,
            "h": 45.34835750330464,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://github.com/inkdrop-org/inkdrop-visualizer"
        },
        "parentId": "page:page",
        "index": "aC",
        "typeName": "shape"
    },
    {
        "x": 3445.1029583728982,
        "y": -250.48463504314594,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:g7CyezO1nc-5AR-FTwmu9",
        "type": "geo",
        "props": {
            "w": 45.05915802460694,
            "h": 45.05915802460694,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://calendly.com/antoine-inkdrop/25-min"
        },
        "parentId": "page:page",
        "index": "aD",
        "typeName": "shape"
    },
    {
        "x": 3445.1029583728982,
        "y": -179.29159089125972,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:T2ibOUtHEsmkcPx_KtVAa",
        "type": "geo",
        "props": {
            "w": 44.474444154792316,
            "h": 44.474444154792316,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://inkdrop.ai"
        },
        "parentId": "page:page",
        "index": "aE",
        "typeName": "shape"
    },
    {
        "x": 1605.8493625292776,
        "y": -509.173528430375,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:tbi-EUy_TFz2_cuYrrhh2",
        "type": "geo",
        "props": {
            "w": 1248.612982417349,
            "h": 457.9160727132356,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "semi",
            "dash": "solid",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "middle",
            "verticalAlign": "middle",
            "growY": 0,
            "url": ""
        },
        "parentId": "page:page",
        "index": "aF",
        "typeName": "shape"
    },
    {
        "x": 1670.4141569486678,
        "y": -441.52073629941526,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:-q-PwczHd26zQX5wykAVp",
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 441.9082299999096,
            "text": "Getting started:",
            "font": "mono",
            "align": "middle",
            "autoSize": true,
            "scale": 3.018267728182068
        },
        "parentId": "page:page",
        "index": "aG",
        "typeName": "shape"
    },
    {
        "x": 1670.4141569486678,
        "y": -343.73357794964204,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:-E1K7m9pDp6oZQtbR_VXS",
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 698.2994437674856,
            "text": "Zoom and pan using your mouse\nUse filters at the top left\nClick on a resource to see additional details",
            "font": "sans",
            "align": "start",
            "autoSize": true,
            "scale": 2.3131087736514435
        },
        "parentId": "page:page",
        "index": "aH",
        "typeName": "shape"
    }
]