import { TLShapeId, TLParentId } from "@tldraw/tldraw";
export const demoShapes = [
    {
        "x": 0,
        "y": 554.5195735987561,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:J5Mx2Ey8yyn7l9SbaGD4Z" as TLShapeId,
        "type": "geo",
        "props": {
            "w": 880.1130060221134,
            "h": 345.1490442290125,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "middle",
            "verticalAlign": "middle",
            "growY": 0,
            "url": ""
        },
        "parentId": "page:page" as TLParentId,
        "index": "a6",
        "typeName": "shape" as "shape"
    },
    {
        "x": 41.59339898484461,
        "y": 614.4340227502584,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:H6D-uV1mY5u7DqtXG7ilC" as TLShapeId,
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 200.5390625,
            "text": "Getting started:",
            "font": "draw",
            "align": "middle",
            "autoSize": true,
            "scale": 1.9096641944628099
        },
        "parentId": "page:page" as TLParentId,
        "index": "a7",
        "typeName": "shape"
    },
    {
        "x": 41.59339898484461,
        "y": 697.5079856865933,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:gq3907AEA7fGtpSL01TNk" as TLShapeId,
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 544.53125,
            "text": "Zoom and pan using your mouse\nUse filters at the top left\nClick on a resource to see additional details",
            "font": "draw",
            "align": "start",
            "autoSize": true,
            "scale": 1.4635086747591146
        },
        "parentId": "page:page" as TLParentId,
        "index": "a8",
        "typeName": "shape"
    },
    {
        "x": 1692.3869939778865,
        "y": 554.5195735987561,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:1wgmobUDyBv1jpMG9N-S8" as TLShapeId,
        "type": "geo",
        "props": {
            "w": 553.8275190361413,
            "h": 345.1490442290125,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "middle",
            "verticalAlign": "middle",
            "growY": 0,
            "url": ""
        },
        "parentId": "page:page" as TLParentId,
        "index": "a9",
        "typeName": "shape"
    },
    {
        "x": 1727.3562452881881,
        "y": 614.4340227502584,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:MHUk-GYvwZMvuSgJG2mS8" as TLShapeId,
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 268.29290007050554,
            "text": "Quick links:",
            "font": "draw",
            "align": "middle",
            "autoSize": true,
            "scale": 1.9096641944628099
        },
        "parentId": "page:page" as TLParentId,
        "index": "aA",
        "typeName": "shape"
    },
    {
        "x": 1733.980392962731,
        "y": 697.5079856865933,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:Kir7mlwA6MEf9OiLY4l0O" as TLShapeId,
        "type": "text",
        "props": {
            "color": "black",
            "size": "m",
            "w": 216.10763641892208,
            "text": "GitHub repo\nBook a call\nWebsite",
            "font": "draw",
            "align": "start",
            "autoSize": true,
            "scale": 1.4635086747591146
        },
        "parentId": "page:page" as TLParentId,
        "index": "aB",
        "typeName": "shape"
    },
    {
        "x": 1967.291095720167,
        "y": 700.8119573316719,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:z4qzFvJ6hRWKXQm_a3rg5" as TLShapeId,
        "type": "geo",
        "props": {
            "w": 44.13959226617101,
            "h": 44.13959226617101,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://github.com/inkdrop-org/inkdrop-visualizer"
        },
        "parentId": "page:page" as TLParentId,
        "index": "aC",
        "typeName": "shape"
    },
    {
        "x": 1967.589162544559,
        "y": 745.7002609556217,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:5b3Mf7BuXj_SuY7ji3BQn" as TLShapeId,
        "type": "geo",
        "props": {
            "w": 44.13959226617101,
            "h": 44.13959226617101,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://calendly.com/antoine-inkdrop/25-min"
        },
        "parentId": "page:page" as TLParentId,
        "index": "aD",
        "typeName": "shape"
    },
    {
        "x": 1967.2192128774825,
        "y": 790.7442462993454,
        "rotation": 0,
        "isLocked": false,
        "opacity": 1,
        "meta": {},
        "id": "shape:EOB040rbuqatcbGa0YdEW" as TLShapeId,
        "type": "geo",
        "props": {
            "w": 44.13959226617101,
            "h": 44.13959226617101,
            "geo": "rectangle",
            "color": "black",
            "labelColor": "black",
            "fill": "none",
            "dash": "draw",
            "size": "m",
            "font": "draw",
            "text": "",
            "align": "start",
            "verticalAlign": "middle",
            "growY": 0,
            "url": "https://inkdrop.ai"
        },
        "parentId": "page:page" as TLParentId,
        "index": "aE",
        "typeName": "shape"
    }
]